version: '2.2'
services:
  streamlit:
    container_name: streamlit
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      APP_URL: http://app:9292
    ports:
      - 8501:8501